# Generated by Django 4.0.5 on 2022-09-08 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(verbose_name='Длинная ссылка')),
                ('short_url', models.URLField(verbose_name='Короткая ссылка')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Переходы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ссылку',
                'verbose_name_plural': 'ссылки',
            },
        ),
    ]
